// app相关
export const SET_USERNAME = 'SET_USERNAME';
export const ADD_TODO = 'ADD_TODO';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_LOADING_WITH_TIMEOUT = 'SHOW_LOADING_WITH_TIMEOUT';